-- In this exercise we will be using the actors table from todays lesson.
-- 1. Count how many actors are in the table. answer 200
-- 2. Try to add a new actor with some blank fields. What do you think the outcome will be ?
--SELECT COUNT(1) FROM actor
--INSERT INTO actor(actor_id, first_name, last_name, last_update) VALUE( , '', '',) error